version: 2
jobs:
  build:

    working_directory: ~/circleci-telegram-bot

    docker:
    - image: circleci/openjdk:8-jdk-browsers
    - image: circleci/mysql:8.0.11
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE=: zayets_bot
    steps:

    - checkout

    - restore_cache:
        key: circleci-telegram-bot-{{ checksum "pom.xml" }}

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: circleci-telegram-bot-{{ checksum "pom.xml" }}

    - run:
        name: Wait for DB
        # preinstalled in circleci/* docker image
        command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
    - run:
        name: Create DATABASE
        command: mysql  -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT  EXISTS `zayets_bot` DEFAULT CHARACTER SET utf8;"
    - run: mvn clean install -Dspring.datasource.password=1234

    - store_test_results:
        path: target/surefire-reports

    - store_artifacts:
        path: target/telegram-bot-1.0.jar